services:
  flask:
    container_name: flask
    build: 
      dockerfile: build/flask.Dockerfile
    command: python ./src/app.py
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5001
    depends_on:
      - db

  db:
    container_name: mysql
    build:
      dockerfile: build/mysql.Dockerfile
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  